name: Deploy Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 1: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_JSON }}'

      # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: turnkey-energy-457517-u4

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 4: Initialize Terraform (with backend)
      - name: Terraform Init
        run: terraform init

      # Step 5: Import Existing Buckets Dynamically
      - name: Terraform Import Existing Buckets
        run: |
          for bucket in $(terraform output -json bucket_names | jq -r '.[]'); do
            terraform import google_storage_bucket.buckets["$bucket"] "$bucket"
          done

      # Step 6: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 7: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
