name: Deploy GCS Buckets

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Step 1: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_JSON }}'

      # ✅ Step 2: Set up gcloud SDK (now already authenticated)
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: turnkey-energy-457517-u4

      # ✅ Step 3: Create GCS bucket
      - name: Create Bucket 1
        run: |
          gsutil mb -p turnkey-energy-457517-u4 -l EU gs://kovas6-bucket-1/
