name: Deploy GCP Buckets

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: turnkey-energy-457517-u4
          service_account_key: ${{ secrets.GCP_CREDENTIALS_JSON }}
          export_default_credentials: true

      - name: Authenticate gcloud with service account
        run: |
          echo "${{ secrets.GCP_CREDENTIALS_JSON }}" > $HOME/gcp-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
          gcloud config set project turnkey-energy-457517-u4

      - name: Create Bucket 1
        run: |
          gsutil mb -p turnkey-energy-457517-u4 -l EU gs://kovas6-bucket-1/

      - name: Create Bucket 2
        run: |
          gsutil mb -p turnkey-energy-457517-u4 -l EU gs://kovas6-bucket-2/
